name = str(input("what is your full name? "))
age = int(input("how old are you? "))
height = float(input("how tall are you? "))

is_learning = True #bool(input("are you learning? (True/False)"))

favorite_language = str(input("what is your favorite coding language? "))
favorite_color = str(input("what is your favorite color? "))

name = name.strip()

# print(f"Name: {name}")
# print(f"Username: {''.join(name.lower().split())}")
# print(f"Name length: {len(name)}")
# print(f"First character: {name[0]}")
# print(f"Last character: {name[-1]}")
# print(f"Contains ")

# print(f"Language: {favorite_language}")
# print(f"Uppercase: {favorite_language.upper()}")
# print(f"Lowercase: {favorite_language.lower()}")
# print(f"Language length: {len(favorite_language)}")
# print(f"Starts with 'Py': {favorite_language.startswith('Py')}")
# print(f"Ends with 'on': {favorite_language.endswith('on')}")

monthly_income = float(input("what is your monthly income? "))
food = float(input("what is your food expenses? "))
transport = float(input("what your transport expenses? "))
other = float(input("what is your other expenses? "))

total_expenses = food + transport + other
remaining_money = monthly_income - total_expenses

savings_percentage = remaining_money / monthly_income * 100
savings_percentage = round(savings_percentage, 2)

print("================================")
print("PERSONAL ANALYZER")
print("================================")
print()
print("PROFILE")
print(f"Name: {name}")
print(f"Username: {''.join(name.lower().split())}")
print(f"Age: {age}")
print(f"Height: {height}")
print(f"Learning Python: {is_learning}")
print(f"Favorite Language: {favorite_language}")
print(f"Favorite Color: {favorite_color}")
print()
print(f"Name length: {len(name)}")
print(f"First character: {name[0]}")
print(f"Last character: {name[-1]}")
print(f"Contains Olori: {'Olori' in name}")
print()
print("LANGUAGE ANALYSIS")
print(f"Language: {favorite_language}")
print(f"Uppercase: {favorite_language.upper()}")
print(f"Lowercase: {favorite_language.lower()}")
print(f"Language length: {len(favorite_language)}")
print(f"Starts with 'Py': {favorite_language.startswith('Py')}")
print(f"Ends with 'on': {favorite_language.endswith('on')}")
print()
print("FINANCIAL ANALYSIS")
print(f"Monthly Income: {monthly_income}")
print(f"Food expenses: {food}")
print(f"Transport expenses: {transport}")
print(f"Other expenses: {other}")
print()
print(f"Total expenses: {total_expenses}")
print(f"Remaining money: {remaining_money}")
print(f"Savings percentage: {savings_percentage}")
print()
print("================================")